---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This is the landing page for the KCM ULB analysis. 

This website contains a number of analyses that have been performed on the KCM data, they can be found below:

* [Vehicle Maintenance Analysis](ulb_analysis.html)
  + Investigates maintenance costs for KCM vehicles give their age and meter mileage
  + Calculates monthly maintenance costs per vehicle type (monthly cost/miles driven)

* Combined Costs Analysis
  + Compares vehicle type replacement cost and maintenance costs 
  + Attempts to determine if there is a consist point in a given vehicle type's life cycle where maintenance costs overcome replacement costs
  + [Combined Costs Analysis_20210426](combined_cost_analysis_20210426.html)
    - Intitial Analysis
  + [Combined Costs Analysis_20210505](combined_cost_analysis_20210503.html)
    - Manual changes to data to increase the quality and quantity of merge operations using vehicle types 
  


